
    %This is the initalization routine for this thing. Builds some
    %structures. k will have be calculated on every call. 
    %I'm keeping the kinetics and the concentrations seperate for now. 
    
    %Alright, what am going to allow to change? And how much of the
    %kinetics am I going to allow in? 
    
    %Basic Photochemical cycle of NOx:
    r_NO_O3 = struct('k','(3.0e-12).*exp(-1500./T)',...
        'loss',{{'NO','O3'}},'gain',struct('name',{'NO2'},'value',{1}),'ksource','S&P');
    r_NO2 = struct('k','0.0067',...
        'loss',{{'NO2'}},'gain',struct('name',{'O3','NO'},'value',{1,1}),'ksource','TUV');
    
    %HOx-NOx Reactions. Unclear what loss processes I'll need to put in. 
    r_NO_HO2 = struct('k', '(3.5e-12).*exp(250./T)',...
        'loss',{{'NO','HO2'}},'gain',struct('name',{'NO2','OH'},'value',{1,1}),'ksource','S&P'); 
    r_HO2_HO2 = struct('k', '((2.3e-13).*exp(600./T) + (1.7e-33).*exp(1000./T).*M)*.5',...
        'loss',{{'HO2','HO2'}},'gain',struct([]),'ksource','S&P'); %don't care about productions
    r_OH_NO2 = struct('k','ThreeBodyK((2.0e-30).*(T./300).^-3.0,(2.5e-11).*(T./300).^-0,M)',...
        'loss',{{'OH','NO2'}},'gain',struct([])); %don't care about products
    
    r_O3_H2O = struct('k','0.78*6e-5',...
        'loss',{{'O3'}},'gain',struct('name',{'OH'},'value',{1}),'ksource','S&P');

    %Isoprene Oxidation Mechanism with HOx. For this system I'm using the Paulot data:
    r_ISOP_OH = struct('k','(2.7e-11).*exp(390./T)',...
        'loss', {{'ISOP','OH'}},'gain',struct('name',{'ISOPOO'},'value',{1}),'ksource','Paulot');

    r_ISOPOO_HO2 = struct('k','(7.4e-13).*exp(700./T)',...
         'gain',struct('name',{'ISOPOOH','OH','OVOC','HO2'},'value',{0.88,.12,.24,.12})...
        ,'ksource','Paulot');
    r_ISOPOOH_OH = struct('k','(1.9e-11).*exp(390./T)',...
        'loss',{{'ISOPOOH','OH'}},'gain',struct('name',{'IEPOX','OH'},'value',{1,1}),'ksource','Paulot');
    
    r_ISOPOOH_OH_a = struct('k','(3.8e-12).*exp(200./T)',...
        'loss',{{'ISOPOOH','OH'}},'gain',struct('name',{'ISOPOO','OVOC','OH'},'value',{0.7,0.3,0.3}),'ksource','Paulot');
    
    r_IEPOX_OH = struct('k','(5.78e-11).*exp(-400./T)',...
        'loss',{{'IEPOX','OH'}},'gain',struct('name',{'IEPOXOO'},'value',{1}),'ksource','Paulot');
    
    rIEPOXOO_HO2 = struct('k','(7.4e-13).*exp(700./T).*1.925',...
        'loss',{{'IEPOXOO','HO2'}},...
        'gain',struct('name',{'OVOC','OH','HO2'},'value',{2,1.125,0.825}),...
        'ksource','Paulot');
    
    r_IEPOXOO_NO = struct('k','(7.6e-12)','loss',{{'IEPOXOO','NO'}},...
        'gain',struct('name',{'NO','HO2','OVOC'},'value',{1,1,1}),'ksource','made_up');
    
    %Very Rough Isoprene + NOx chemistry:
    r_ISOPOO_NO = struct('k', '2.54e-12.*exp(360./T)',...
        'loss',{{'ISOPOO','NO'}},...
        'gain',struct('name',{'NO','HO2','OVOC','AN'},'value',{0.93,0.93,0.93,0.07}),...
        'ksource','LaFranchi');
    
        
    %OVOC Chemistry Mechanism: 
    %Now I haven't exactly included OVOCOO + HO2 products here. That's
%     %probably something I should fix. 
%     r_OVOC_OH = struct('k','(6.0e-12).*exp(380./T)',...
%         'loss',{{'OVOC','OH'}},'gain',struct('name',{'OVOCOO'},'value',{1}),'ksource','LaFranchi'); %SImilar to MACR
%     r_OVOCOO_HO2 = struct('k','2.9e-13.*exp(1300./T)',...
%         'loss',{{'OVOCOO','HO2'}},'gain',struct([]),'ksrouce','LaFranchi');%Not quite sure if this is right. 
%     
%     r_OVOCOO_NO = struct('k','(8.1e-12).*exp(270./T)',...
%         'loss',{{'OVOCOO','NO'}},...
%         'gain',struct('name',{'NO2','HO2','AN'},'value',{0.85,0.85,0.15}));    
%     
%     r_OVOCOO_NO2 = struct('k','ThreeBodyK((9.7e-12).*(T./300).^-5.6,(9.3e-12).*(T./300).^-1.5,M)',...
%         'loss',{{'OVOCOO','NO2'}},'gain',struct('name',{'PAN'},'value',{1}),'ksource','IUPAC??');
%     r_PAN = struct('k','ThreeBodyK((9.7e-12).*(T./300).^-5.6,(9.3e-12).*(T./300).^-1.5,M)./((9.0e-29).*exp(14000./T))',...
%         'loss',{{'PAN'}},'gain',struct('name',{'OVOCOO','NO2'},'value',{1,1}),'ksource','IUPAC??');
%     

    %RO2_RO2 chemical losses:
    r_ISOPOO_ISOOPOO = struct('k',' 2.4e-12',...
        'loss',{{'ISOPOO','ISOPOO'}},'gain',struct([]),'ksrouce','LaFranchi');
    
%     r_OVOCOO_OVOCOO = struct('k','2.4e-12',...
%         'loss',{{'OVOCOO','OVOCOO'}},'gain',{{}},'ksrouce','LaFranchi');
%     
%     r_ISOPOO_OVOCOO = struct('k','2.4e-12',...
%         'loss',{{'ISOPOO','OVOCOO'}},'gain',{{}},'ksrouce','LaFranchi');
%   
    
    %This run is not going to include nighttime reactions